### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by gabrielbdornas** [gabrielbdornas/date-math#1]
**Estrutura do projeto**

- [ ] Criar LICENCE.txt
- [ ] Criar MANIFEST.in
- [ ] Criar CHANGELOG.md
- [ ] Criar o arquivo setup.py
- [ ] Criar arquivo make
- [ ] Criar pasta data_math (ficará nosso código)

**Código**
- [ ] Criar um arquivo para as funções;
- [ ] Criar um arquivo para chamar a função CLI (adição e subtração)

**Publicação**
- [ ] Criar teste automatizado para todas as funções do pacote
- [ ]  Testar manualmente o código
- [ ] Publicar [Pypi](https://pypi.org/)
- [ ] Comemorar :beers:
